#!/usr/bin/env php
<?php


// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

// Composer
require __DIR__ . '/../vendor/autoload.php';

// Environment
require __DIR__ . '/../common/Environment.php';
$environment = new Environment([
    //'envVar'=>'YII_ENV',
    //'env'=>null,
    //'debugVar'=>'YII_DEBUG',
    //'debug'=>null,
]);


require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/../common/config/bootstrap.php';

require __DIR__ . '/../console/config/bootstrap.php';

// App
require __DIR__ . '/../common/AppInstance.php';
AppInstance::systemInit();

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/../common/config/main.php',
    require __DIR__ . '/../common/config/main-local.php',
    require __DIR__ . '/../console/config/main.php',
    require __DIR__ . '/../console/config/main-local.php'
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
